-- MySQL Script generated by MySQL Workbench
-- Wed May  6 22:19:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `senior`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `senior` ;

CREATE TABLE IF NOT EXISTS `senior` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cart` ;

CREATE TABLE IF NOT EXISTS `cart` (
  `idcart` INT NOT NULL AUTO_INCREMENT,
  `time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `time_done` TIMESTAMP NULL,
  `done` TINYINT(1) NOT NULL,
  `user_id` INT NULL,
  `senior_id` INT NOT NULL,
  PRIMARY KEY (`idcart`),
  INDEX `fk_cart_user_idx` (`user_id` ASC),
  INDEX `fk_cart_senior1_idx` (`senior_id` ASC),
  CONSTRAINT `fk_cart_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_senior1`
    FOREIGN KEY (`senior_id`)
    REFERENCES `senior` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cartItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cartItem` ;

CREATE TABLE IF NOT EXISTS `cartItem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `item` VARCHAR(45) NOT NULL,
  `cart_id` INT NOT NULL, 
  PRIMARY KEY (`id`),
  INDEX `fk_cartItem_cart1_idx` (`cart_id` ASC),
  CONSTRAINT `fk_cartItem_cart1`
    FOREIGN KEY (`cart_id`)
    REFERENCES `cart` (`idcart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
